import path from 'node:path';
import { SessionMemory, SessionAnalysis, SessionData } from './types.js';

/**
 * Generates a model-agnostic project context document from session memory
 * and current session data. This is the LOCAL/deterministic version — used
 * when the backend is unavailable. The backend produces a richer AI-generated
 * version via /api/session/context.
 *
 * This context is designed to be seeded into ANY AI tool's system prompt
 * (Claude, Cursor, Copilot, Gemini, Codex, etc.) without modification.
 */
export function generateProjectContext(
  memory: SessionMemory,
  session: SessionData,
  analysis: SessionAnalysis,
  projectName: string,
  previousContext: string | null
): string {
  const lines: string[] = [];

  lines.push("# Project Context");
  lines.push("");
  lines.push(`> Auto-generated by Worktrace. Last updated: ${new Date().toISOString()}`);
  lines.push("");

  // --- Architecture Decisions (from previous context + current session signals) ---
  lines.push("## Architecture Decisions");
  lines.push("");

  // Carry forward previous decisions if they exist
  const prevDecisions = previousContext
    ? extractSection(previousContext, "Architecture Decisions")
    : null;

  if (prevDecisions) {
    lines.push(prevDecisions);
  }

  // Detect new architecture signals from this session
  const newDecisions = inferArchitectureDecisions(session, analysis);
  if (newDecisions.length > 0) {
    if (prevDecisions) {
      lines.push("");
      lines.push("*New this session:*");
    }
    newDecisions.forEach((d) => lines.push(`- ${d}`));
  }

  if (!prevDecisions && newDecisions.length === 0) {
    lines.push("*(Will be populated as sessions accumulate.)*");
  }
  lines.push("");

  // --- Key Modules & Files ---
  lines.push("## Key Modules & Files");
  lines.push("");

  const keyFiles = analysis.primaryFocusFiles.slice(0, 15);
  if (keyFiles.length > 0) {
    lines.push("| File | Purpose |");
    lines.push("| --- | --- |");
    keyFiles.forEach((f) => {
      lines.push(`| \`${f.file}\` | ${f.reason} |`);
    });
  }

  // Add churn hotspots as important files
  if (memory.churnHotspots.length > 0) {
    lines.push("");
    lines.push("**High-churn files** (frequently modified across sessions):");
    memory.churnHotspots.slice(0, 5).forEach((h) => {
      lines.push(`- \`${h.file}\` — ${h.sessionCount} sessions, ${h.totalSaves} total saves`);
    });
  }
  lines.push("");

  // --- Current Roadmap ---
  lines.push("## Current Roadmap");
  lines.push("");

  lines.push("**In Progress:**");
  lines.push(`- ${analysis.intentDescription} (branch: \`${session.branch || "unknown"}\`, ${analysis.sessionMode} mode)`);
  lines.push("");

  lines.push("**Next Up:**");
  if (analysis.tomorrowChecklist.length > 0) {
    analysis.tomorrowChecklist.slice(0, 5).forEach((t) => {
      lines.push(`- ${t}`);
    });
  } else {
    lines.push("- *(No pending items)*");
  }
  lines.push("");

  // Carry forward previous "Recently Completed" if available
  const prevCompleted = previousContext
    ? extractBulletList(previousContext, "Recently Completed")
    : null;
  if (prevCompleted) {
    lines.push("**Recently Completed:**");
    lines.push(prevCompleted);
    lines.push("");
  }

  // --- What Failed / What to Avoid ---
  lines.push("## What Failed / What to Avoid");
  lines.push("");

  // Carry forward previous failures
  const prevFailures = previousContext
    ? extractSection(previousContext, "What Failed / What to Avoid")
    : null;

  if (prevFailures) {
    lines.push(prevFailures);
  }

  // Add current friction as potential failure signals
  const meaningfulFriction = analysis.frictionPoints.filter(
    (p) => !p.includes("No significant friction")
  );
  if (meaningfulFriction.length > 0) {
    if (prevFailures) {
      lines.push("");
      lines.push("*This session:*");
    }
    meaningfulFriction.forEach((f) => lines.push(`- ${f}`));
  }

  // Add recurring friction from cross-session memory
  if (memory.recurringFriction.length > 0) {
    lines.push("");
    lines.push("**Recurring friction** (appears across multiple sessions):");
    memory.recurringFriction.forEach((f) => lines.push(`- ${f}`));
  }

  if (!prevFailures && meaningfulFriction.length === 0 && memory.recurringFriction.length === 0) {
    lines.push("*(No friction or failures recorded yet.)*");
  }
  lines.push("");

  // --- Next Steps ---
  lines.push("## Next Steps");
  lines.push("");

  // Open TODOs from previous sessions
  if (memory.openTodos.length > 0) {
    lines.push("*Carried from previous sessions:*");
    memory.openTodos.slice(0, 5).forEach((todo, i) => {
      lines.push(`${i + 1}. ${todo}`);
    });
    lines.push("");
  }

  // Current session's tomorrow checklist
  if (analysis.tomorrowChecklist.length > 0) {
    lines.push("*From this session:*");
    analysis.tomorrowChecklist.slice(0, 5).forEach((t, i) => {
      const offset = memory.openTodos.length > 0 ? memory.openTodos.length + i + 1 : i + 1;
      lines.push(`${offset}. ${t}`);
    });
    lines.push("");
  }

  // --- Active Branch Context ---
  lines.push("## Active Branch Context");
  lines.push("");
  lines.push(`- **Current branch:** \`${session.branch || "unknown"}\``);

  if (memory.recentBranches.length > 0) {
    const otherBranches = memory.recentBranches.filter((b) => b !== session.branch);
    if (otherBranches.length > 0) {
      lines.push(`- **Recent branches:** ${otherBranches.slice(0, 5).map((b) => `\`${b}\``).join(", ")}`);
    }
  }

  // Session count context
  lines.push(`- **Total sessions tracked:** ${memory.totalSessions}`);
  lines.push("");

  return lines.join("\n");
}

/**
 * Extract a section's content from a previous context document.
 * Looks for ## heading and captures until next ## or end.
 */
function extractSection(context: string, heading: string): string | null {
  const regex = new RegExp(
    `## ${escapeRegex(heading)}\\n([\\s\\S]*?)(?=\\n## |$)`,
    "m"
  );
  const match = context.match(regex);
  if (!match) return null;
  const content = match[1].trim();
  return content || null;
}

/**
 * Extract bullet list items under a bold label from previous context.
 */
function extractBulletList(context: string, label: string): string | null {
  const regex = new RegExp(
    `\\*\\*${escapeRegex(label)}:?\\*\\*\\n([\\s\\S]*?)(?=\\n\\*\\*|\\n## |$)`,
    "m"
  );
  const match = context.match(regex);
  if (!match) return null;
  const content = match[1].trim();
  return content || null;
}

function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Infer architecture decisions from session data.
 * These are signals, not AI-generated — the backend prompt does the real analysis.
 */
function inferArchitectureDecisions(
  session: SessionData,
  analysis: SessionAnalysis
): string[] {
  const decisions: string[] = [];

  // Detect new module creation
  const newModules = analysis.delta.created.filter(
    (f) => f.file.endsWith(".ts") || f.file.endsWith(".tsx") || f.file.endsWith(".js")
  );
  if (newModules.length > 0) {
    const moduleNames = newModules.slice(0, 3).map((f) => `\`${path.basename(f.file)}\``);
    decisions.push(`New module(s) introduced: ${moduleNames.join(", ")}`);
  }

  // Detect deletions that imply refactoring
  if (analysis.delta.deleted.length > 0) {
    const deletedFiles = analysis.delta.deleted.slice(0, 3).map((d) => `\`${path.basename(d.file)}\``);
    decisions.push(`Removed: ${deletedFiles.join(", ")} — check for migration/consolidation pattern`);
  }

  // Detect config/build changes
  const configFiles = session.filesTouched.filter((f) =>
    /^(tsconfig|package|webpack|vite|rollup|docker|\.env)/i.test(path.basename(f))
  );
  if (configFiles.length > 0) {
    decisions.push(`Build/config changes: ${configFiles.slice(0, 3).map((f) => `\`${path.basename(f)}\``).join(", ")}`);
  }

  return decisions;
}
