import { SessionData, SessionAnalysis, SafetyWarning } from "./types";

export function renderSessionMemory(
  session: SessionData,
  analysis: SessionAnalysis,
  safetyWarnings: SafetyWarning[] = []
): string {
  const s: string[] = [];

  s.push("# Worktrace Session Report");
  s.push("");
  s.push(`> Generated by [Worktrace](https://github.com/ivasuy/cursor-sm) \u2014 the operating system for AI-assisted development`);
  s.push("");

  // Session overview block
  s.push("## Session Overview");
  s.push("");
  s.push(`| Field | Value |`);
  s.push(`| --- | --- |`);
  s.push(`| **Mode** | ${analysis.sessionMode} |`);
  s.push(`| **Confidence** | ${analysis.confidence.level} \u2014 ${analysis.confidence.explanation} |`);
  s.push(`| **Branch** | \`${session.branch || "unknown"}\` |`);
  s.push(`| **Duration** | ${formatDuration(session.startTime, session.endTime)} |`);
  s.push(`| **Intent** | ${analysis.intentDescription} |`);
  s.push(`| **Files Touched** | ${session.filesTouched.length} |`);
  s.push("");

  // Safety Warnings (new section)
  if (safetyWarnings.length > 0) {
    s.push("---");
    s.push("");
    s.push("## \u26A0\uFE0F Safety Warnings");
    s.push("");

    const critical = safetyWarnings.filter((w) => w.severity === "critical");
    const warnings = safetyWarnings.filter((w) => w.severity === "warning");
    const infos = safetyWarnings.filter((w) => w.severity === "info");

    if (critical.length > 0) {
      s.push("### Critical");
      s.push("");
      critical.forEach((w) => {
        s.push(`- **[${w.category}]** ${w.message}${w.file ? ` in \`${w.file}\`` : ""}${w.line ? ` (line: \`${w.line}\`)` : ""}`);
      });
      s.push("");
    }

    if (warnings.length > 0) {
      s.push("### Warnings");
      s.push("");
      warnings.forEach((w) => {
        s.push(`- **[${w.category}]** ${w.message}${w.file ? ` in \`${w.file}\`` : ""}${w.line ? ` (line: \`${w.line}\`)` : ""}`);
      });
      s.push("");
    }

    if (infos.length > 0) {
      s.push("### Info");
      s.push("");
      infos.forEach((w) => {
        s.push(`- **[${w.category}]** ${w.message}${w.file ? ` in \`${w.file}\`` : ""}`);
      });
      s.push("");
    }
  }

  // Files Changed
  s.push("---");
  s.push("");
  s.push("## Files Changed");
  s.push("");

  if (analysis.delta.created.length > 0) {
    s.push("### Created");
    s.push("");
    analysis.delta.created.forEach((f) => {
      s.push(`- **${f.file}**`);
      if (f.content.length > 0) {
        s.push("  ```");
        f.content.slice(0, 10).forEach((line) => s.push(`  ${line}`));
        if (f.content.length > 10) {
          s.push(`  ... (+${f.content.length - 10} more lines)`);
        }
        s.push("  ```");
      }
    });
    s.push("");
  }

  if (analysis.delta.updated.length > 0) {
    s.push("### Updated");
    s.push("");
    analysis.delta.updated.forEach((f) => {
      s.push(`- **${f.file}** \u2014 +${f.added} / -${f.removed}`);
      if (f.addedLines.length > 0) {
        s.push("  Added:");
        s.push("  ```");
        f.addedLines
          .slice(0, 5)
          .forEach((line) => s.push(`  + ${line}`));
        if (f.addedLines.length > 5) {
          s.push(`  ... (+${f.addedLines.length - 5} more)`);
        }
        s.push("  ```");
      }
      if (f.removedLines.length > 0) {
        s.push("  Removed:");
        s.push("  ```");
        f.removedLines
          .slice(0, 5)
          .forEach((line) => s.push(`  - ${line}`));
        if (f.removedLines.length > 5) {
          s.push(`  ... (+${f.removedLines.length - 5} more)`);
        }
        s.push("  ```");
      }
    });
    s.push("");
  }

  if (analysis.delta.deleted.length > 0) {
    s.push("### Deleted");
    s.push("");
    analysis.delta.deleted.forEach((d) => {
      s.push(`- ~~${d.file}~~`);
      if (d.affectedFiles.length > 0) {
        s.push(
          `  - Affected: ${d.affectedFiles.map((a) => a.file).join(", ")}`
        );
      }
    });
    s.push("");
  }

  if (
    analysis.delta.created.length === 0 &&
    analysis.delta.updated.length === 0 &&
    analysis.delta.deleted.length === 0
  ) {
    s.push("No file changes detected in diff.");
    s.push("");
  }

  // Primary Focus Files
  if (analysis.primaryFocusFiles.length > 0) {
    s.push("### Primary Focus");
    s.push("");
    analysis.primaryFocusFiles.forEach((f) => {
      s.push(`- **${f.file}** \u2014 ${f.reason}`);
    });
    s.push("");
  }

  // Session Timeline
  if (session.fileChangeEvents.length > 0) {
    s.push("---");
    s.push("");
    s.push("## Session Timeline");
    s.push("");
    const events = session.fileChangeEvents;
    const startTime = Date.parse(session.startTime);
    const bucketSize = 5 * 60 * 1000; // 5 minute buckets
    const buckets = new Map<number, number>();

    events.forEach((e) => {
      const t = Date.parse(e.timestamp);
      const bucket = Math.floor((t - startTime) / bucketSize);
      buckets.set(bucket, (buckets.get(bucket) || 0) + 1);
    });

    if (buckets.size > 1) {
      const maxBucket = Math.max(...buckets.values());
      const sortedBuckets = Array.from(buckets.entries()).sort((a, b) => a[0] - b[0]);

      sortedBuckets.forEach(([bucket, count]) => {
        const mins = bucket * 5;
        const label = mins < 60
          ? `${mins}m`
          : `${Math.floor(mins / 60)}h${mins % 60 > 0 ? `${mins % 60}m` : ""}`;
        const barLength = Math.round((count / maxBucket) * 20);
        const bar = "\u2588".repeat(barLength) + "\u2591".repeat(20 - barLength);
        s.push(`\`${label.padStart(5)}\` ${bar} ${count} events`);
      });
      s.push("");
    }
  }

  // Where I Got Stuck
  s.push("---");
  s.push("");
  s.push("## Where I Got Stuck");
  s.push("");
  analysis.frictionPoints.forEach((p) => s.push(`- ${p}`));
  s.push("");

  // Tomorrow, First 10 Minutes
  s.push("---");
  s.push("");
  s.push("## Tomorrow, First 10 Minutes");
  s.push("");
  analysis.tomorrowChecklist.forEach((item, i) =>
    s.push(`${i + 1}. ${item}`)
  );
  s.push("");

  // What I Explicitly Didn't Touch
  s.push("---");
  s.push("");
  s.push("## What I Explicitly Didn't Touch");
  s.push("");
  analysis.explicitlyDidntTouch.forEach((u) => s.push(`- ${u}`));
  s.push("");

  // My Note
  s.push("---");
  s.push("");
  s.push("## My Note");
  s.push("");
  if (analysis.userNote) {
    s.push(analysis.userNote);
  } else {
    s.push(
      "*(No note added. Use 'Worktrace: Add Session Note' command during your session.)*"
    );
  }
  s.push("");

  return s.join("\n");
}

function formatDuration(startTime: string, endTime: string | null): string {
  const start = Date.parse(startTime);
  const end = endTime ? Date.parse(endTime) : Date.now();
  const mins = Math.round((end - start) / 60000);
  if (mins < 1) {
    return "< 1 minute";
  }
  if (mins < 60) {
    return `${mins} minutes`;
  }
  const hrs = Math.floor(mins / 60);
  const remainMins = mins % 60;
  return `${hrs}h ${remainMins}m`;
}
