import { SessionData, SessionAnalysis, SafetyWarning, SessionMemory, CodeChangeSummary } from "./types";

export type RenderOptions = {
  session: SessionData;
  analysis: SessionAnalysis;
  safetyWarnings: SafetyWarning[];
  codeChanges?: CodeChangeSummary[];
  memory?: SessionMemory;
  contextBlock?: string;
};

export function renderSessionMemory(options: RenderOptions): string {
  const { session, analysis, safetyWarnings, codeChanges, memory, contextBlock } = options;
  const s: string[] = [];

  s.push("# Worktrace Session Report");
  s.push("");
  s.push(`> Generated by [Worktrace](https://github.com/ivasuy/cursor-sm) \u2014 the operating system for AI-assisted development`);
  s.push("");

  // Session overview block — enriched
  const totalSaves = Object.values(session.saveCounts).reduce((a, b) => a + b, 0);
  const totalLinesAdded = [...analysis.delta.created, ...analysis.delta.updated].reduce(
    (sum, f) => sum + ("added" in f ? f.added : f.content.length),
    0
  );
  const totalLinesRemoved = analysis.delta.updated.reduce((sum, f) => sum + f.removed, 0);

  s.push("## Session Overview");
  s.push("");
  s.push(`| Field | Value |`);
  s.push(`| --- | --- |`);
  s.push(`| **Mode** | ${analysis.sessionMode} |`);
  s.push(`| **Confidence** | ${analysis.confidence.level} \u2014 ${analysis.confidence.explanation} |`);
  s.push(`| **Branch** | \`${session.branch || "unknown"}\` |`);
  s.push(`| **Duration** | ${formatDuration(session.startTime, session.endTime)} |`);
  s.push(`| **Intent** | ${analysis.intentDescription} |`);
  s.push(`| **Files Touched** | ${session.filesTouched.length} |`);
  s.push(`| **Total Saves** | ${totalSaves} |`);
  s.push(`| **Lines +/-** | +${totalLinesAdded} / -${totalLinesRemoved} |`);
  s.push(`| **Created / Updated / Deleted** | ${analysis.delta.created.length} / ${analysis.delta.updated.length} / ${analysis.delta.deleted.length} |`);
  s.push("");

  // Session Narrative
  s.push("---");
  s.push("");
  s.push("## Session Narrative");
  s.push("");
  s.push(buildNarrative(session, analysis, safetyWarnings, totalSaves, totalLinesAdded));
  s.push("");

  // Safety Warnings with inline context
  if (safetyWarnings.length > 0) {
    s.push("---");
    s.push("");
    s.push("## \u26A0\uFE0F Safety Warnings");
    s.push("");

    const critical = safetyWarnings.filter((w) => w.severity === "critical");
    const warnings = safetyWarnings.filter((w) => w.severity === "warning");
    const infos = safetyWarnings.filter((w) => w.severity === "info");

    if (critical.length > 0) {
      s.push("### Critical");
      s.push("");
      critical.forEach((w) => {
        s.push(`- **[${w.category}]** ${w.message}${w.file ? ` in \`${w.file}\`` : ""}`);
        if (w.context && w.context.length > 0) {
          s.push("  ```");
          w.context.forEach((line, idx) => {
            const marker = w.lineIndex !== undefined && idx === Math.min(w.lineIndex, 2) ? " \u2190 \u26A0\uFE0F" : "";
            s.push(`  ${line}${marker}`);
          });
          s.push("  ```");
        }
      });
      s.push("");
    }

    if (warnings.length > 0) {
      s.push("### Warnings");
      s.push("");
      warnings.forEach((w) => {
        s.push(`- **[${w.category}]** ${w.message}${w.file ? ` in \`${w.file}\`` : ""}`);
        if (w.context && w.context.length > 0) {
          s.push("  ```");
          w.context.forEach((line, idx) => {
            const marker = w.lineIndex !== undefined && idx === Math.min(w.lineIndex, 2) ? " \u2190 \u26A0\uFE0F" : "";
            s.push(`  ${line}${marker}`);
          });
          s.push("  ```");
        }
      });
      s.push("");
    }

    if (infos.length > 0) {
      s.push("### Info");
      s.push("");
      infos.forEach((w) => {
        s.push(`- **[${w.category}]** ${w.message}${w.file ? ` in \`${w.file}\`` : ""}`);
      });
      s.push("");
    }
  }

  // Files Changed with inline vulnerability markers
  s.push("---");
  s.push("");
  s.push("## Files Changed");
  s.push("");

  // Build warning lookup: file -> lineIndex -> warning
  const warningsByFile = new Map<string, Map<number, SafetyWarning>>();
  for (const w of safetyWarnings) {
    if (w.file && w.lineIndex !== undefined) {
      if (!warningsByFile.has(w.file)) {
        warningsByFile.set(w.file, new Map());
      }
      warningsByFile.get(w.file)!.set(w.lineIndex, w);
    }
  }

  if (analysis.delta.created.length > 0) {
    s.push("### Created");
    s.push("");
    analysis.delta.created.forEach((f) => {
      s.push(`- **${f.file}**`);
      if (f.content.length > 0) {
        s.push("  ```");
        f.content.slice(0, 10).forEach((line) => s.push(`  ${line}`));
        if (f.content.length > 10) {
          s.push(`  ... (+${f.content.length - 10} more lines)`);
        }
        s.push("  ```");
      }
    });
    s.push("");
  }

  if (analysis.delta.updated.length > 0) {
    s.push("### Updated");
    s.push("");
    analysis.delta.updated.forEach((f) => {
      s.push(`- **${f.file}** \u2014 +${f.added} / -${f.removed}`);
      const fileWarnings = warningsByFile.get(f.file);
      if (f.addedLines.length > 0) {
        s.push("  Added:");
        s.push("  ```");
        f.addedLines
          .slice(0, 10)
          .forEach((line, idx) => {
            const w = fileWarnings?.get(idx);
            const marker = w ? `  \u26A0 [${w.severity.toUpperCase()}: ${w.category}] ${w.message}` : "";
            s.push(`  + ${line}${marker}`);
          });
        if (f.addedLines.length > 10) {
          s.push(`  ... (+${f.addedLines.length - 10} more)`);
        }
        s.push("  ```");
      }
      if (f.removedLines.length > 0) {
        s.push("  Removed:");
        s.push("  ```");
        f.removedLines
          .slice(0, 10)
          .forEach((line) => s.push(`  - ${line}`));
        if (f.removedLines.length > 10) {
          s.push(`  ... (+${f.removedLines.length - 10} more)`);
        }
        s.push("  ```");
      }
    });
    s.push("");
  }

  if (analysis.delta.deleted.length > 0) {
    s.push("### Deleted");
    s.push("");
    analysis.delta.deleted.forEach((d) => {
      s.push(`- ~~${d.file}~~`);
      if (d.affectedFiles.length > 0) {
        s.push(
          `  - Affected: ${d.affectedFiles.map((a) => a.file).join(", ")}`
        );
      }
    });
    s.push("");
  }

  if (
    analysis.delta.created.length === 0 &&
    analysis.delta.updated.length === 0 &&
    analysis.delta.deleted.length === 0
  ) {
    s.push("No file changes detected in diff.");
    s.push("");
  }

  // Code Change Summary
  if (codeChanges && codeChanges.length > 0) {
    const withFunctions = codeChanges.filter((c) => c.functionsAdded.length > 0 || c.importsChanged);
    if (withFunctions.length > 0) {
      s.push("---");
      s.push("");
      s.push("## Code Change Summary");
      s.push("");
      s.push("| File | +/- | Functions Added | Imports |");
      s.push("| --- | --- | --- | --- |");
      withFunctions.forEach((c) => {
        const funcs = c.functionsAdded.length > 0 ? c.functionsAdded.map((f) => `\`${f}\``).join(", ") : "\u2014";
        const imports = c.importsChanged ? "Changed" : "\u2014";
        s.push(`| \`${c.file}\` | +${c.linesAdded}/-${c.linesRemoved} | ${funcs} | ${imports} |`);
      });
      s.push("");
    }
  }

  // Primary Focus Files
  if (analysis.primaryFocusFiles.length > 0) {
    s.push("### Primary Focus");
    s.push("");
    analysis.primaryFocusFiles.forEach((f) => {
      s.push(`- **${f.file}** \u2014 ${f.reason}`);
    });
    s.push("");
  }

  // Session Timeline
  if (session.fileChangeEvents.length > 0) {
    s.push("---");
    s.push("");
    s.push("## Session Timeline");
    s.push("");
    const events = session.fileChangeEvents;
    const startTime = Date.parse(session.startTime);
    const bucketSize = 5 * 60 * 1000;
    const buckets = new Map<number, number>();

    events.forEach((e) => {
      const t = Date.parse(e.timestamp);
      const bucket = Math.floor((t - startTime) / bucketSize);
      buckets.set(bucket, (buckets.get(bucket) || 0) + 1);
    });

    if (buckets.size > 1) {
      const maxBucket = Math.max(...buckets.values());
      const sortedBuckets = Array.from(buckets.entries()).sort((a, b) => a[0] - b[0]);

      sortedBuckets.forEach(([bucket, count]) => {
        const mins = bucket * 5;
        const label = mins < 60
          ? `${mins}m`
          : `${Math.floor(mins / 60)}h${mins % 60 > 0 ? `${mins % 60}m` : ""}`;
        const barLength = Math.round((count / maxBucket) * 20);
        const bar = "\u2588".repeat(barLength) + "\u2591".repeat(20 - barLength);
        s.push(`\`${label.padStart(5)}\` ${bar} ${count} events`);
      });
      s.push("");
    }
  }

  // Where I Got Stuck
  s.push("---");
  s.push("");
  s.push("## Where I Got Stuck");
  s.push("");
  analysis.frictionPoints.forEach((p) => s.push(`- ${p}`));
  s.push("");

  // Tomorrow, First 10 Minutes
  s.push("---");
  s.push("");
  s.push("## Tomorrow, First 10 Minutes");
  s.push("");
  analysis.tomorrowChecklist.forEach((item, i) =>
    s.push(`${i + 1}. ${item}`)
  );
  s.push("");

  // Cross-Session Insights
  if (memory && memory.totalSessions > 1) {
    s.push("---");
    s.push("");
    s.push("## Cross-Session Insights");
    s.push("");

    s.push(`- **Sessions on this branch:** ${countBranchSessions(memory, session.branch)}`);
    s.push(`- **Total sessions tracked:** ${memory.totalSessions}`);

    if (memory.churnHotspots.length > 0) {
      s.push("");
      s.push("**Churn hotspots** (files touched across multiple sessions):");
      memory.churnHotspots.slice(0, 5).forEach((h) => {
        s.push(`- \`${h.file}\` \u2014 ${h.sessionCount} sessions, ${h.totalSaves} total saves`);
      });
    }

    if (memory.recurringFriction.length > 0) {
      s.push("");
      s.push("**Recurring friction patterns:**");
      memory.recurringFriction.forEach((f) => {
        s.push(`- ${f}`);
      });
    }

    if (memory.openTodos.length > 0) {
      s.push("");
      s.push("**Open items from previous sessions:**");
      memory.openTodos.slice(0, 5).forEach((t) => {
        s.push(`- ${t}`);
      });
    }
    s.push("");
  }

  // What I Explicitly Didn't Touch
  s.push("---");
  s.push("");
  s.push("## What I Explicitly Didn't Touch");
  s.push("");
  analysis.explicitlyDidntTouch.forEach((u) => s.push(`- ${u}`));
  s.push("");

  // My Note
  s.push("---");
  s.push("");
  s.push("## My Note");
  s.push("");
  if (analysis.userNote) {
    s.push(analysis.userNote);
  } else {
    s.push(
      "*(No note added. Use 'Worktrace: Add Session Note' command during your session.)*"
    );
  }
  s.push("");

  // AI Context Block
  if (contextBlock) {
    s.push("---");
    s.push("");
    s.push("## AI Context Block");
    s.push("");
    s.push("<details>");
    s.push("<summary>Expand for AI-ready context</summary>");
    s.push("");
    s.push(contextBlock);
    s.push("");
    s.push("</details>");
    s.push("");
  }

  return s.join("\n");
}

function buildNarrative(
  session: SessionData,
  analysis: SessionAnalysis,
  warnings: SafetyWarning[],
  totalSaves: number,
  totalLinesAdded: number
): string {
  const parts: string[] = [];
  const duration = formatDuration(session.startTime, session.endTime);
  const fileCount = session.filesTouched.length;

  parts.push(
    `This was a ${duration} session in \`${analysis.sessionMode}\` mode, touching ${fileCount} file${fileCount !== 1 ? "s" : ""} with ${totalSaves} save${totalSaves !== 1 ? "s" : ""} and +${totalLinesAdded} lines added.`
  );

  if (analysis.confidence.level === "Low") {
    parts.push(`Session confidence is **Low** (${analysis.confidence.explanation}), suggesting unfinished work.`);
  } else if (analysis.confidence.level === "High") {
    parts.push("Session confidence is **High** \u2014 work appears clean and focused.");
  }

  const criticalCount = warnings.filter((w) => w.severity === "critical").length;
  const frictionCount = analysis.frictionPoints.filter(
    (p) => !p.includes("No significant friction")
  ).length;

  if (criticalCount > 0) {
    parts.push(`\u26A0\uFE0F ${criticalCount} critical safety issue${criticalCount > 1 ? "s" : ""} detected \u2014 review before committing.`);
  }
  if (frictionCount > 0) {
    parts.push(`${frictionCount} friction point${frictionCount > 1 ? "s" : ""} identified during the session.`);
  }

  return parts.join(" ");
}

function countBranchSessions(memory: SessionMemory, branch: string | null): number {
  if (!branch || !memory.recentBranches) {
    return 1;
  }
  return memory.recentBranches.filter((b) => b === branch).length + 1;
}

function formatDuration(startTime: string, endTime: string | null): string {
  const start = Date.parse(startTime);
  const end = endTime ? Date.parse(endTime) : Date.now();
  const mins = Math.round((end - start) / 60000);
  if (mins < 1) {
    return "< 1 minute";
  }
  if (mins < 60) {
    return `${mins} minutes`;
  }
  const hrs = Math.floor(mins / 60);
  const remainMins = mins % 60;
  return `${hrs}h ${remainMins}m`;
}
